### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by treeowl** [haskell-primitive/primitive-unlifted#21]
I started contributing to this package because I wanted to use it to implement an idea for `persistent-vector`. I'm now nearly ready to do so.

**Comment by andrewthad** [comment]
If you're comfortable with where it is now, I can release a new version. I'll bump to 1.0.0.0 because of how extensive the changes are.

**Comment by treeowl** [comment]
I'm not guaranteeing there are no bugs or mistakes, but yeah, I think it's a good resting point. I expect I'll get to the remaining types later; there's not much urgency on my end.

**Comment by treeowl** [comment]
Any progress?

**Comment by andrewthad** [comment]
Changes have been released to hackage as version 1.0.0.0.
