### ISSUE TITLE
Update 0.1.x.x series for GHC 9.2.1

### ISSUE THREAD

**Issue by cumber** [haskell-primitive/primitive-unlifted#26]
Since the changelog says:

> Stay on the 0.1.x.x series unless you need something from this newer version.

I thought it might be worthwhile to make a new release based on 0.1.3 that builds with GHC 9.2.1.

I've made a patch (builds and passes tests with GHCs 9.2.1, 9.0.1, and 8.10.7), but since there isn't an actual branch for the 0.1.x.x series I don't seem to be able to make an actual pull request. You can see what I propose here: https://github.com/haskell-primitive/primitive-unlifted/compare/00d1a44246779a17e0651005df062264f20b4b6e...cumber:0.1-series-ghc-9.2.1

I tried the same technique with current master, but I get a GHC panic (!) when I try to build, so I don't have a working pull request there.

**Comment by andrewthad** [comment]
This looks good. Could you open a PR with that change. I'd be happy to release that as a 0.1.3.1.

**Comment by cumber** [comment]
I tried, but it'll only let me make a pull request onto a branch tip; a pull request on master will try to revert all of your changes to get to 1.0.0.0, as well as apply my changes.

If you made a branch for the 0.1 series (at the commit where you released 0.1.3.0), I could make a pull request on top of that branch.

**Comment by andrewthad** [comment]
I've created a branched named `soundness` that you should now be able to PR to.

**Comment by cumber** [comment]
Done! #27
