### ISSUE TITLE
Revert to pre-1.0.0.0 state

### ISSUE THREAD

**Issue by andrewthad** [haskell-primitive/primitive-unlifted#33]
The changes in `primitive-unlifted-1.0.0.0` do not work with GHC 9.0, 9.2, or 9.4. I'm planning on releasing a version `primitive-unlifted-2.0.0.0` that just brings everything back to the way it is in `primitive-unlifted-0.1.3.1`.

**Comment by treeowl** [comment]
Shouldn't it be possible to do everything *properly* now that we have the appropriate primitive types and primops?

**Comment by andrewthad** [comment]
I'd forgotten about that. I think you're right. If we drop support for everything before 9.4, then I think this could be done correctly.

**Comment by treeowl** [comment]
I've opened a PR: #34 . That was a slog, but I think you'll be pleased.

**Comment by treeowl** [comment]
Can we close this now, thanks to #34, and move on to the great reimagining?

**Comment by andrewthad** [comment]
Yes.
