### ISSUE TITLE
Bump bounds to allow bytestring-0.12

### ISSUE THREAD

**Issue by wz1000** [haskell-primitive/primitive-unlifted#39]
The package builds without any further changes.

**Comment by juhp** [comment]
A Hackage revision would be good too.

I can help with that if needed

(this is blocking HLS from building with ghc-9.8)

**Comment by juhp** [comment]
I made a Hackage [revision](https://hackage.haskell.org/package/primitive-unlifted-2.1.0.0/revisions/) as a Trustee
